Repository AY2425S1-CS2103T-T12-4/tp, pull requests merged in 2024-10, with the labels that each got.

#22 Add Matthew's Photo
  docs/images/flyingsalsa.png
Labels: priority.Medium

#17 Add Xiangcheng's photo
  docs/AboutUs.md
  docs/images/xczheng0105.png
Labels: priority.Medium

#19 Update AboutUs page
  docs/AboutUs.md
Labels: priority.Medium

#49 Branch update app logo
  docs/images/Logo.png
  docs/site.json
Labels: priority.Medium

#57 Add game model
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/game/Game.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGame.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#58 Update Ui to include games
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/address_book_32old.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#70 Add Username class
  src/main/java/seedu/address/logic/commands/UsernameCommand.java
Labels: priority.High

#77 Change person to store games as a hashmap
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UsernameCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#78 Add preferred time
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/preferredtime/Day.java
  src/main/java/seedu/address/model/preferredtime/PreferredTime.java
  src/main/java/seedu/address/model/preferredtime/Time.java
  src/test/java/seedu/address/model/preferredtime/DayTest.java
  src/test/java/seedu/address/model/preferredtime/PreferredTimeTest.java
  src/test/java/seedu/address/model/preferredtime/TimeTest.java
Labels: priority.Medium

#92 Edit game command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditGameCommand.java
  src/main/java/seedu/address/logic/commands/UsernameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/game/Game.java
Labels: priority.High

#93 Implement parser logic
  src/main/java/seedu/address/logic/commands/EditGameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditGameCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/game/Role.java
  src/main/java/seedu/address/model/game/SkillLevel.java
  src/main/java/seedu/address/model/game/Username.java
Labels: priority.High

#89 Update help window
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium

#102 Branch UI changes
  src/main/java/seedu/address/logic/commands/EditGameCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/GameLabelGenerator.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#87 Update add command in User Guide
  docs/UserGuide.md
Labels: priority.High

#104 UI issues from editgame
  src/main/java/seedu/address/logic/commands/EditGameCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/GameLabelGenerator.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#105 Fix case sensitive games in editgame
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.Low

#108 Minor bug fixes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditGameCommand.java
Labels: priority.Medium

#112 Fix Game name using tag name constraints
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#117 Fix a bug related to editing in a new game
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#122 Add Command history navigation
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandHistory.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/ui/CommandHistoryTest.java
Labels: priority.High

#129 Add support for favourite games
  src/main/java/seedu/address/logic/commands/EditGameCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteGameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavouriteGameCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/game/Game.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGame.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#131 Implement FindTimeCommand and link to AddressBookParser
  src/main/java/seedu/address/logic/commands/FindTimeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTimeCommandParser.java
  src/main/java/seedu/address/model/preferredtime/PreferredTime.java
  src/main/java/seedu/address/model/preferredtime/PreferredTimeOverlapsRangesPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindTimeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindTimeCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#127 Update 'save' and 'load' commands in User Guide
  docs/UserGuide.md
Labels: priority.High

#136 Branch puml file changes
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Low

#135 Branch command pop up window
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/commandpopup/AutoSuggestionTextField.java
  src/main/java/seedu/address/ui/commandpopup/CommandTextFlow.java
  src/main/java/seedu/address/ui/commandpopup/PopUpCommandsSet.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/ui/commandpopup/CommandTextFlowTest.java
Labels: priority.Medium

#137 Fix minor bugs
  src/main/java/seedu/address/logic/parser/FavouriteGameCommandParser.java
  src/main/java/seedu/address/logic/parser/UnfavouriteGameCommandParser.java
Labels: priority.High

#145 Update DG and puml with undo command
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagramNew-Logic.puml
Labels: priority.High

#173 #140 command pop up updates
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/commandpopup/CommandTextFlow.java
  src/main/java/seedu/address/ui/commandpopup/PopUpCommandsSet.java
  src/test/java/seedu/address/ui/commandpopup/CommandTextFlowTest.java
Labels: alpha-bug

#174 Branch update documentation
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/commandpopup.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: alpha-bug

#176 Help window fixes
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: alpha-bug

#200 Alpha bug fix
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: alpha-bug
